name: SpeedBoost
main: com.neverseenbefore.weja.speedboost.SpeedBoost
version: 0.3

permissions:
    speedboost.*:
        description: Gives Speed Boost III
        children:
            speedboost.speedboost.three: false
    speedboost.speedboost.three:
        description: Gives Speed Boost III
        default: false
